### ISSUE TITLE
Doesn't show on Redmine 5.0.4

### ISSUE THREAD

**Issue by rdemendoza** [fraoustin/redmine_closed_date#3]
Hi,
I have no error on the logs, but it doesn't at all :(

**Comment by rdemendoza** [comment]
version '0.1.1' (can't fine the 0.1.2)

**Comment by fraoustin** [comment]
Hi 
the version 0.1.2 does not exist, the version 0.1.1 is good

I use Docker for test

My Dockerfile

> FROM redmine:5.0.4
> WORKDIR /usr/src/redmine/plugins
> RUN git clone https://github.com/fraoustin/redmine_default_due.git
> RUN git clone https://github.com/fraoustin/redmine_closed_date.git
> WORKDIR /usr/src/redmine/


I build and run my image


> docker nuild -t test .
> docker run --name test -p 3000:3000 test


I connect to 127.0.0.1:3000

I have a redmine with version 5.0.4

![image](https://user-images.githubusercontent.com/3457495/218300986-1ffaad6b-16e4-41f5-ac80-eaebdd9e867d.png)

the plugin is active

![image](https://user-images.githubusercontent.com/3457495/218302255-07e395ec-c09e-4348-92ea-3f7c4c9bb50d.png)

I created a project and after a demand and after I close the demand

![image](https://user-images.githubusercontent.com/3457495/218302315-398f7367-2d44-4848-9c5c-4ba913d962cb.png)

For me all is ok

Have you the plugin in the plugin administration?

Do you use docker ?

Where you have copied the files of the plugins?

We are going to found a solution ;-)

**Comment by rdemendoza** [comment]
Hi,
the version 0.1.2 it listed on: https://www.redmine.org/plugins/redmine_closed_date
So when you search for updates you get:
<img width="699" alt="version" src="https://user-images.githubusercontent.com/11791031/218344971-9c2c10f9-4844-4b03-85df-81f928bc6d47.png">
<img width="234" alt="hint" src="https://user-images.githubusercontent.com/11791031/218345028-eae53461-db37-40df-ade0-f17ecb83ff32.png">

**Comment by rdemendoza** [comment]
We don't use docker, we are on a self-hosted Ubuntu 22.04.

Here is my configuration:
<img width="590" alt="infos" src="https://user-images.githubusercontent.com/11791031/218345107-32e94e84-321a-42dc-94a1-a9e08bdb5461.png">

The files are in: plugins/redmine_closed_date

The plugin is active:
<img width="874" alt="Capture d’écran 2023-02-13 à 01 02 32" src="https://user-images.githubusercontent.com/11791031/218345217-3e892af0-e328-4b6b-a333-0a01548948b1.png">

But I don't see the field:
<img width="798" alt="closed" src="https://user-images.githubusercontent.com/11791031/218345384-0ff9393f-f129-4eb4-b8d8-15f81686fb89.png">

I have no error in the logs...

Thanks in advance :)

**Comment by rdemendoza** [comment]
After doing theses commands it works :)
```
bundle exec rake deface:precompile RAILS_ENV=production
bundle exec rake deface:clean RAILS_ENV=production
```

**Comment by fraoustin** [comment]
update the README
